/**
 * The recorded backend platform — what it is CALLED, and what KIND of thing it is.
 *
 * `IndexRow.pf` / `record.platform` is a single detected fact per church, and it
 * is the console's only signal about what software a church already runs. Two
 * things were wrong with how it was being used, and this module fixes both.
 *
 * ── 1 · A THIRD OF THE VOCABULARY HAD NO NAME ──
 *
 * `VOCAB.BACKEND_NAME` covers 7 of the 19 values the corpus actually contains.
 * `platformLine()` looks a value up and pushes nothing when it misses, so 1,908
 * churches (12.5%) had a KNOWN backend that appeared nowhere in the product —
 * not in the list line, not in the dossier. Silent, and indistinguishable from
 * "we never detected one".
 *
 * The names are patched here rather than in `vocab.generated.ts`, which is
 * generated by executing `core.js` and would lose them on the next regeneration.
 * Same reasoning and same shape as `ANSWER_LABEL_PATCH` in `labels.ts`.
 *
 * ── 2 · `pf` IS NOT A ChMS FIELD ──
 *
 * It is "the backend we detected", and the 19 values are four different kinds of
 * product: church management systems, giving processors, media libraries and
 * SMS tools. Offering them as one "ChMS" filter would tell a salesperson that
 * 517 churches run RightNow Media as their church management system, which is a
 * video library.
 *
 * So there are two facets over one field, and A VENDOR MAY APPEAR IN BOTH —
 * several of these companies genuinely sell both halves, and forcing a single
 * bucket would hide a real Tithe.ly ChMS church from the ChMS filter or a real
 * Tithe.ly giving church from the tooling one.
 *
 * The classification is a judgement about products, not a fact the pipeline
 * measured, so it lives in one table with a reason per line and is meant to be
 * argued with.
 */

import { VOCAB } from "./vocab.generated.ts";

const BACKEND_NAME = VOCAB.BACKEND_NAME as Record<string, string>;

/** Display names for the values `BACKEND_NAME` does not carry. */
const BACKEND_NAME_PATCH: Record<string, string> = {
  rightnowmedia: "RightNow Media",
  pushpay: "Pushpay",
  givelify: "Givelify",
  churchtrac: "ChurchTrac",
  vanco: "Vanco",
  ministrybrands: "Ministry Brands",
  fellowshipone: "Fellowship One",
  textinchurch: "Text In Church",
  rockrms: "Rock RMS",
  clearstream: "Clearstream",
  faithlife: "Faithlife",
};

/** The name to show, or "" when the value is absent or explicitly unknown. */
export function backendName(key: string | undefined | null): string {
  const k = (key ?? "").toLowerCase();
  if (!k || k === "unknown") return "";
  return BACKEND_NAME_PATCH[k] ?? BACKEND_NAME[k] ?? "";
}

export type BackendKind = "chms" | "tooling";

/**
 * What each backend IS. A vendor selling both appears under both.
 *
 * `chms`    church management — people, groups, attendance, membership
 * `tooling` everything else we detect: giving, media, messaging, apps
 */
export const BACKEND_KINDS: Record<string, readonly BackendKind[]> = {
  // ── church management, unambiguously ──
  church_center: ["chms"], // Planning Center
  realm: ["chms"], // ACS Realm
  breeze: ["chms"],
  ccb: ["chms"], // Church Community Builder
  churchtrac: ["chms"],
  elvanto: ["chms"],
  fellowshipone: ["chms"],
  rockrms: ["chms"],

  // ── both halves are real products ──
  // Giving first and by far the better known, but Tithe.ly ChMS is a genuine
  // church management product and 1,871 churches is too many to guess about.
  tithely: ["chms", "tooling"],
  // Apps, media and giving — and church management alongside them.
  subsplash: ["chms", "tooling"],
  // A holding company whose portfolio is ChMS products (Elexio, Servant Keeper,
  // Shelby) plus giving and websites. The detected key says which vendor, not
  // which product.
  ministrybrands: ["chms", "tooling"],
  // Faithlife sells church management next to its media and giving products.
  faithlife: ["chms", "tooling"],

  // ── not church management ──
  pushpay: ["tooling"], // giving. It OWNS ccb, but ccb is its own key here.
  givelify: ["tooling"], // giving
  vanco: ["tooling"], // payments
  rightnowmedia: ["tooling"], // discipleship video library
  textinchurch: ["tooling"], // SMS + email
  clearstream: ["tooling"], // SMS
};

/** Does this backend belong in the given facet? */
export function backendIsKind(key: string | undefined | null, kind: BackendKind): boolean {
  const k = (key ?? "").toLowerCase();
  if (!k || k === "unknown") return false;
  return (BACKEND_KINDS[k] ?? []).includes(kind);
}
