/**
 * THE M0 GATE.
 *
 * `fixture/golden-colors.json` was generated by EXECUTING the real `colorState`,
 * `favorScore` and `favorCount` out of `core.js`, with default tuning and no
 * colour overrides. Every church x 10 questions, plus a favorScore and a
 * favorCount each — 152,740 cells against the current corpus of 15,274, and it
 * was 1,340 against the 134-church sample this was written for.
 *
 * The counts are stated as an ORDER OF MAGNITUDE, not as an assertion: the
 * corpus is republished and the sizes move, so the test below asserts that the
 * golden table and the index cover the same churches rather than that there is
 * some particular number of them.
 *
 * Zero mismatches, or the port is wrong. This is the cheapest possible proof
 * that the most load-bearing logic in the product survived the rewrite, and it
 * catches a precedence bug in `colorState` that no amount of clicking would.
 *
 * IT RUNS TWICE — once from the full records, once from the slim index.
 *
 * That second pass is not redundant. The list, the facet swatches and the
 * histogram are drawn from the index while the dossier is drawn from the record,
 * so a projection that disagrees paints one colour in the list and another in
 * the dossier for the same church. That is the incident the "one source of truth
 * for (question, answer) -> colour" rule exists for, and it is exactly what the
 * index's missing q6 field would have caused. See `adapt.ts`.
 */

import { test, describe } from "node:test";
import assert from "node:assert/strict";

import {
  churchFromIndex,
  churchFromRecord,
  type ChurchView,
} from "../adapt.ts";
import { colorState } from "../color.ts";
import { favorBase, favorCount, favorMax, favorScore, referenceFavorModel } from "../favor.ts";
import { stepsDisplayCount } from "../steps.ts";
import { QMETA, type EngineCtx, type QuestionKey } from "../types.ts";
import { HAVE_FIXTURE, loadGolden, loadIndex, loadRecord } from "./fixture.mts";

const QUESTION_KEYS = QMETA.map(([k]) => k as QuestionKey);

/**
 * WHERE WE HAVE DELIBERATELY STOPPED MATCHING THE REFERENCE.
 *
 * Written out here as a literal, INDEPENDENTLY of `COLOR_PATCH` in `color.ts`
 * and deliberately not imported from it. Importing would make this test say
 * "the code agrees with itself", which is not a fact about anything. Two
 * separate statements of intent mean an unannounced recolour still turns the
 * gate red, and an announced one has to be written down twice — once as
 * behaviour, once as a decision with a reason.
 *
 * `golden-colors.json` stays untouched. It records what the reference `core.js`
 * does, and it has to keep doing that to be worth running.
 */
const DIVERGES: Record<string, string> = {
  // A confirmed custom login is `bad`, so a possible one is the "likely" grade
  // of the same finding rather than an unverified signal. The reference says
  // `unver`, whose wording promises a check that was retired upstream.
  // Owner decision. The test below proves it still bites on real churches, so
  // no count is written here to go stale against the next publish.
  "q5:custom_candidate": "bad2",
};

/**
 * REFERENCE tuning, no overrides — the exact conditions golden-colors.json was
 * built under.
 *
 * Deliberately NOT `defaultFavorModel()`. That is the owner's shipped tuning and
 * it moves whenever the product's mind changes about who buys; this table is a
 * proof that the PORT is faithful, and it must not turn red because someone
 * decided mega-churches are worth two points after all.
 */
function makeCtx(rows: ReturnType<typeof loadIndex>): EngineCtx {
  return { overrides: {}, favor: referenceFavorModel(), rows };
}

describe("golden colour + favor table", { skip: !HAVE_FIXTURE && "fixture not present" }, () => {
  const index = loadIndex();
  const golden = loadGolden();
  const ctx = makeCtx(index);
  const ids = Object.keys(golden.churches);

  /**
   * The index and the golden table must describe THE SAME CORPUS.
   *
   * This used to assert `=== 134`, which stopped being a fact the day the
   * fixture became the real operating list and would have to be re-typed after
   * every publish. The number was never the point: what a hard-coded count
   * actually caught was a truncated fixture, and set equality catches that plus
   * the failure a literal could not — a `golden-colors.json` left behind from a
   * different build, which is a live risk now that both files are regenerated
   * together and land as separate bytes in the same package.
   */
  test("the golden table and the index describe the same churches", () => {
    assert.ok(index.length > 0, "the fixture is empty");
    const inIndex = new Set(index.map((r) => r.id));
    const onlyGolden = ids.filter((id) => !inIndex.has(id));
    const onlyIndex = [...inIndex].filter((id) => !golden.churches[id]);
    assert.deepEqual(onlyGolden.slice(0, 10), [], `${onlyGolden.length} golden ids not in the index`);
    assert.deepEqual(onlyIndex.slice(0, 10), [], `${onlyIndex.length} index ids not in the golden table`);
    assert.equal(QUESTION_KEYS.length, 10);
  });

  test("the two denominators are derived, not hard-coded", () => {
    const favor = referenceFavorModel();
    // A church can legitimately score ABOVE favorBase — it is the most you can
    // reach without the custom-website and app opportunities, not a ceiling.
    assert.equal(favorBase(favor), golden.favorBase, "favorBase");
    assert.equal(favorMax(favor), golden.favorMax, "favorMax");
    assert.ok(favorMax(favor) > favorBase(favor), "favorMax must exceed favorBase");
  });

  /**
   * One projection, checked cell by cell. Failures are collected rather than
   * thrown on the first, so a precedence bug reports its whole blast radius
   * instead of one arbitrary church.
   */
  /** The reference value, unless this pair is a sanctioned divergence. */
  const expected = (id: string, k: QuestionKey, view: ChurchView) =>
    DIVERGES[`${k}:${view.q(k)?.answer}`] ?? golden.churches[id].cells[k];

  function checkProjection(label: string, viewFor: (id: string) => ChurchView) {
    describe(label, () => {
      test("every cell matches", () => {
        const bad: string[] = [];
        for (const id of ids) {
          const view = viewFor(id);
          for (const k of QUESTION_KEYS) {
            const got = colorState(k, view.q(k), ctx);
            const want = expected(id, k, view);
            if (got !== want) bad.push(`${id} ${k}: got ${got}, want ${want}`);
          }
        }
        assert.deepEqual(
          bad.slice(0, 25),
          [],
          `${bad.length} of ${ids.length * QUESTION_KEYS.length} cells wrong` +
            (bad.length > 25 ? " (first 25 shown)" : ""),
        );
      });

      test("every favorScore matches", () => {
        const bad: string[] = [];
        for (const id of ids) {
          const got = favorScore(viewFor(id), ctx);
          const want = golden.churches[id].favorScore;
          // Float sum of 0.3125-style weights: compare at the 2dp the UI shows.
          if (Math.abs(got - want) > 1e-9) bad.push(`${id}: got ${got}, want ${want}`);
        }
        assert.deepEqual(bad.slice(0, 25), [], `${bad.length} favorScore values wrong`);
      });

      test("every favorCount matches", () => {
        const bad: string[] = [];
        for (const id of ids) {
          const got = favorCount(viewFor(id), ctx);
          const want = golden.churches[id].favorCount;
          if (got !== want) bad.push(`${id}: got ${got}, want ${want}`);
        }
        assert.deepEqual(bad.slice(0, 25), [], `${bad.length} favorCount values wrong`);
      });

      /**
       * The golden table stores `steps: null` — not 0 — for the two churches
       * whose next-step pages were never read. That IS the "not checked, never
       * 0 of 8" rule, expressed in the data. Comparing raw `nPresent` here would
       * pass a build that renders a zero where it must render "not checked".
       */
      test("every displayed next-step count matches, and unlooked stays null", () => {
        const bad: string[] = [];
        for (const id of ids) {
          const got = stepsDisplayCount(viewFor(id).steps);
          const want = golden.churches[id].steps ?? null;
          if (got !== want) bad.push(`${id}: got ${got}, want ${want}`);
        }
        assert.deepEqual(bad.slice(0, 25), [], `${bad.length} step counts wrong`);
      });

      test("every platform line matches", () => {
        const bad: string[] = [];
        for (const id of ids) {
          const got = viewFor(id).platformLine;
          const want = golden.churches[id].platformLine;
          if (got !== want) bad.push(`${id}: got ${JSON.stringify(got)}, want ${JSON.stringify(want)}`);
        }
        assert.deepEqual(bad.slice(0, 25), [], `${bad.length} platform lines wrong`);
      });
    });
  }

  const byId = new Map(index.map((r) => [r.id, r]));

  checkProjection("from the full record", (id) => churchFromRecord(loadRecord(id)));
  checkProjection("from the slim index", (id) => churchFromIndex(byId.get(id)!));

  /**
   * Every sanctioned divergence must actually bite.
   *
   * Without this the list is write-only: an entry whose answer value no longer
   * exists, or which someone quietly reverted in `color.ts`, would sit here
   * looking like a deliberate decision while changing nothing — and the next
   * person would read it as documentation of behaviour that is not happening.
   */
  test("each declared divergence applies to real churches, and only where declared", () => {
    for (const [pair, want] of Object.entries(DIVERGES)) {
      const [k, answer] = pair.split(":") as [QuestionKey, string];
      const hit = ids.filter((id) => churchFromRecord(loadRecord(id)).q(k)?.answer === answer);
      assert.ok(hit.length > 0, `${pair} matches no church — the divergence is dead`);
      for (const id of hit) {
        const view = churchFromRecord(loadRecord(id));
        assert.equal(colorState(k, view.q(k), ctx), want, `${id} ${pair}`);
        assert.notEqual(
          golden.churches[id].cells[k],
          want,
          `${pair} is not a divergence — the reference already says ${want}`,
        );
      }
    }
  });

  /**
   * THE REASON THE RECOLOUR IS SAFE, asserted rather than assumed.
   *
   * `favorScore` awards full points for `good`, half for `good2`, and nothing
   * for anything else — so moving an answer between two zero-scoring states
   * must not move a single church's score. The two favor tests above compare
   * against the untouched reference table; this states out loud what makes that
   * still valid, so a future divergence into `good`/`good2` fails HERE, with an
   * explanation, rather than as 134 mysterious favor mismatches.
   */
  test("no divergence moves a church's favor score", () => {
    const scoring = new Set(["good", "good2"]);
    for (const [pair, want] of Object.entries(DIVERGES)) {
      const from = golden.churches[
        ids.find((id) => {
          const a = churchFromRecord(loadRecord(id)).q(pair.split(":")[0] as QuestionKey)?.answer;
          return a === pair.split(":")[1];
        })!
      ].cells[pair.split(":")[0]];
      assert.equal(
        scoring.has(from) || scoring.has(want),
        false,
        `${pair}: ${from} → ${want} crosses the scoring boundary, so favorScore moves`,
      );
    }
  });

  /**
   * The two projections must agree with EACH OTHER, not merely with the table.
   * A future index field that quietly stops being published would show up here
   * first, and this is the assertion that makes the list and the dossier
   * incapable of disagreeing.
   */
  test("the record and index projections agree on every cell", () => {
    const bad: string[] = [];
    for (const id of ids) {
      const a = churchFromRecord(loadRecord(id));
      const b = churchFromIndex(byId.get(id)!);
      for (const k of QUESTION_KEYS) {
        const ca = colorState(k, a.q(k), ctx);
        const cb = colorState(k, b.q(k), ctx);
        if (ca !== cb) bad.push(`${id} ${k}: record ${ca} vs index ${cb}`);
      }
      if (a.country !== b.country) bad.push(`${id} country: ${a.country} vs ${b.country}`);
      if (stepsDisplayCount(a.steps) !== stepsDisplayCount(b.steps))
        bad.push(`${id} steps: record vs index`);
      if (a.name !== b.name) bad.push(`${id} name: ${a.name} vs ${b.name}`);
    }
    assert.deepEqual(bad.slice(0, 25), [], `${bad.length} disagreements between projections`);
  });

  /**
   * The subdivision is the ONE field where the two sources genuinely disagree,
   * and the disagreement is upstream data loss rather than a projection bug:
   * where the scrape spelled a state out in full, the index builder wrote only
   * the country. The record keeps it, the index cannot recover it.
   *
   * This used to pin the exact two churches, which was a sharp assertion about a
   * 134-church sample and merely a list of names once the corpus became the real
   * one. What it was really protecting is the SHAPE of the disagreement, so that
   * is what is asserted now: the index may be SILENT where the record speaks —
   * that is the known upstream loss — but it may never speak DIFFERENTLY. A
   * record saying TX and an index saying MS is a projection bug and would put a
   * church in the wrong filter; a record saying TX and an index saying nothing
   * only drops it from the dropdown, which is the documented cost.
   */
  test("the index may drop a subdivision but never contradict one", () => {
    const contradictions: string[] = [];
    let upstream = 0;
    let dropped = 0;
    for (const id of ids) {
      const rec = loadRecord(id);
      const row = byId.get(id)!;
      const a = churchFromRecord(rec).subdiv;
      const b = churchFromIndex(row).subdiv;
      if (a === b) continue;
      if (!a || !b) {
        dropped++;
        continue;
      }
      /**
       * THE TWO FIELDS HAVE DIFFERENT FORMATS BY DESIGN, which is why a naive
       * "same input, same output" check gets this backwards.
       *
       *   record  profile.location = "Newton, NC"  -> subdivision is field [1]
       *   index   rg               = "NC, USA"     -> subdivision is field [0]
       *
       * So the readers deliberately take opposite tokens, and identical raw
       * strings are themselves the anomaly: `tokyo_metro_church_jp` carries
       * "国立市, 東京都" in BOTH, and the two faithful readers land on the
       * municipality and the prefecture respectively. That is upstream writing
       * `rg` in the record's format for one church, not a bug in `region.ts`.
       *
       * Counted rather than asserted away, so the day it stops being one church
       * somebody sees it.
       */
      upstream++;
      contradictions.push(`${id}: record ${a} vs index ${b} (raw "${(rec.profile?.location as string) ?? ""}" / "${row.rg ?? ""}")`);
    }
    assert.ok(dropped < ids.length, `every subdivision was dropped (${dropped})`);
    assert.ok(
      upstream < ids.length / 1000,
      `${upstream} churches resolve to two different subdivisions — a data report, ` +
        `not a code fix:\n  ${contradictions.slice(0, 10).join("\n  ")}`,
    );
  });

  /**
   * THE DISCIPLESHIP PROJECTION, BOTH WAYS.
   *
   * The list tile reads `dp`/`dps` off the index; the dossier card reads the
   * pathway out of the full record. Same church, two sources, and if they
   * disagree one surface says "None" while the other says "Not checked" — the
   * precise failure this whole describe block exists to make impossible for
   * colours, applied to the question the tile was just built for.
   *
   * The XOR is asserted rather than trusted. A row carrying neither field falls
   * to "unknown" and under-reports silently; a row carrying both means the
   * projection has two opinions and whichever the code reads first wins.
   */
  test("the index and the record agree about the discipleship pathway", () => {
    const bad: string[] = [];
    const both: string[] = [];
    const neither: string[] = [];
    const tally: Record<string, number> = { has: 0, none: 0, unknown: 0 };

    for (const id of ids) {
      const row = byId.get(id)!;
      if (row.dp != null && row.dps != null) both.push(id);
      if (row.dp == null && row.dps == null) neither.push(id);

      const fromIndex = churchFromIndex(row);
      const fromRecord = churchFromRecord(loadRecord(id));
      tally[fromIndex.pathway]++;

      if (fromIndex.pathway !== fromRecord.pathway) {
        bad.push(`${id}: index ${fromIndex.pathway} vs record ${fromRecord.pathway}`);
      } else if (fromIndex.pathwaySteps !== fromRecord.pathwaySteps) {
        bad.push(`${id}: index ${fromIndex.pathwaySteps} steps vs record ${fromRecord.pathwaySteps}`);
      }
    }

    assert.deepEqual(both.slice(0, 10), [], `${both.length} rows carry BOTH dp and dps`);
    assert.deepEqual(neither.slice(0, 10), [], `${neither.length} rows carry NEITHER dp nor dps`);
    assert.deepEqual(bad.slice(0, 15), [], `${bad.length} churches disagree across the two sources`);

    // All three states must actually occur, or the tile is showing one colour
    // for a reason nobody would notice.
    for (const state of ["has", "none", "unknown"]) {
      assert.ok(tally[state] > 0, `no church reads "${state}" — the three states have collapsed`);
    }
  });

  /**
   * "None" IS A CLAIM. Only `model_says_no` earns it: we read the site and it
   * publishes no pathway. Every other absence — above all the churches our
   * detector never asked about, which is the largest group in the corpus — must
   * read "not checked", or the console asserts an absence nobody measured.
   */
  test('only a measured negative may read "none"', () => {
    const overclaimed: string[] = [];
    for (const id of ids) {
      const row = byId.get(id)!;
      if (churchFromIndex(row).pathway !== "none") continue;
      if (row.dps !== "model_says_no") overclaimed.push(`${id}: dps=${row.dps}`);
    }
    assert.deepEqual(
      overclaimed.slice(0, 15),
      [],
      `${overclaimed.length} churches would read "None" without a measured negative behind it`,
    );
  });

  /** A country code must never leak into the subdivision dropdown. */
  test("no subdivision value is a country", () => {
    const countries = new Set(index.map((r) => r.co).filter(Boolean));
    const subdivs = new Set(
      index.map((r) => churchFromIndex(r).subdiv).filter(Boolean),
    );
    for (const c of countries) {
      assert.ok(!subdivs.has(c!), `"${c}" is a country and must not be offered as a subdivision`);
    }
  });

  /**
   * q6 specifically, because it is the one the shipped index could not paint and
   * the one an `adapt.ts` refactor would silently re-break. A regression turns
   * churches grey in the list while the dossier still shows them coloured —
   * which reads as missing data rather than as a bug.
   *
   * Asserted as agreement rather than as a tally of three numbers. The tally was
   * a description of one sample; what must hold on any corpus is that the two
   * sources paint the same church the same colour, and that the index has not
   * collapsed the question to grey wholesale.
   */
  test("q6 paints from the index, not grey (the documented index gap)", () => {
    const disagree: string[] = [];
    let good = 0;
    for (const id of ids) {
      const fromIndex = colorState("q6", churchFromIndex(byId.get(id)!).q("q6"), ctx);
      const fromRecord = colorState("q6", churchFromRecord(loadRecord(id)).q("q6"), ctx);
      if (fromIndex !== fromRecord) disagree.push(`${id}: index ${fromIndex} vs record ${fromRecord}`);
      if (fromIndex === "good") good++;
    }
    assert.deepEqual(disagree.slice(0, 10), [], `${disagree.length} churches paint q6 differently`);
    assert.ok(good > 0, "no church reads good from the index — q6 has collapsed to grey again");
  });
});
