/**
 * THE M0 GATE.
 *
 * `fixture/golden-colors.json` was generated by EXECUTING the real `colorState`,
 * `favorScore` and `favorCount` out of `core.js`, with default tuning and no
 * colour overrides. 134 churches x 10 questions = 1,340 cells, plus 134
 * favorScore and 134 favorCount values.
 *
 * Zero mismatches, or the port is wrong. This is the cheapest possible proof
 * that the most load-bearing logic in the product survived the rewrite, and it
 * catches a precedence bug in `colorState` that no amount of clicking would.
 *
 * IT RUNS TWICE — once from the full records, once from the slim index.
 *
 * That second pass is not redundant. The list, the facet swatches and the
 * histogram are drawn from the index while the dossier is drawn from the record,
 * so a projection that disagrees paints one colour in the list and another in
 * the dossier for the same church. That is the incident the "one source of truth
 * for (question, answer) -> colour" rule exists for, and it is exactly what the
 * index's missing q6 field would have caused. See `adapt.ts`.
 */

import { test, describe } from "node:test";
import assert from "node:assert/strict";

import {
  churchFromIndex,
  churchFromRecord,
  type ChurchView,
} from "../adapt.ts";
import { colorState } from "../color.ts";
import { favorBase, favorCount, favorMax, favorScore, referenceFavorModel } from "../favor.ts";
import { stepsDisplayCount } from "../steps.ts";
import { QMETA, type EngineCtx, type QuestionKey } from "../types.ts";
import { HAVE_FIXTURE, loadGolden, loadIndex, loadRecord } from "./fixture.mts";

const QUESTION_KEYS = QMETA.map(([k]) => k as QuestionKey);

/**
 * WHERE WE HAVE DELIBERATELY STOPPED MATCHING THE REFERENCE.
 *
 * Written out here as a literal, INDEPENDENTLY of `COLOR_PATCH` in `color.ts`
 * and deliberately not imported from it. Importing would make this test say
 * "the code agrees with itself", which is not a fact about anything. Two
 * separate statements of intent mean an unannounced recolour still turns the
 * gate red, and an announced one has to be written down twice — once as
 * behaviour, once as a decision with a reason.
 *
 * `golden-colors.json` stays untouched. It records what the reference `core.js`
 * does, and it has to keep doing that to be worth running.
 */
const DIVERGES: Record<string, string> = {
  // A confirmed custom login is `bad`, so a possible one is the "likely" grade
  // of the same finding rather than an unverified signal. The reference says
  // `unver`, whose wording promises a check that was retired upstream.
  // 22 of 134 churches. Owner decision.
  "q5:custom_candidate": "bad2",
};

/**
 * REFERENCE tuning, no overrides — the exact conditions golden-colors.json was
 * built under.
 *
 * Deliberately NOT `defaultFavorModel()`. That is the owner's shipped tuning and
 * it moves whenever the product's mind changes about who buys; this table is a
 * proof that the PORT is faithful, and it must not turn red because someone
 * decided mega-churches are worth two points after all.
 */
function makeCtx(rows: ReturnType<typeof loadIndex>): EngineCtx {
  return { overrides: {}, favor: referenceFavorModel(), rows };
}

describe("golden colour + favor table", { skip: !HAVE_FIXTURE && "fixture not present" }, () => {
  const index = loadIndex();
  const golden = loadGolden();
  const ctx = makeCtx(index);
  const ids = Object.keys(golden.churches);

  test("the fixture is the size the handoff says it is", () => {
    assert.equal(index.length, 134, "slim index should hold 134 churches");
    assert.equal(ids.length, 134, "golden table should hold 134 churches");
    assert.equal(QUESTION_KEYS.length, 10);
  });

  test("the two denominators are derived, not hard-coded", () => {
    const favor = referenceFavorModel();
    // A church can legitimately score ABOVE favorBase — it is the most you can
    // reach without the custom-website and app opportunities, not a ceiling.
    assert.equal(favorBase(favor), golden.favorBase, "favorBase");
    assert.equal(favorMax(favor), golden.favorMax, "favorMax");
    assert.ok(favorMax(favor) > favorBase(favor), "favorMax must exceed favorBase");
  });

  /**
   * One projection, checked cell by cell. Failures are collected rather than
   * thrown on the first, so a precedence bug reports its whole blast radius
   * instead of one arbitrary church.
   */
  /** The reference value, unless this pair is a sanctioned divergence. */
  const expected = (id: string, k: QuestionKey, view: ChurchView) =>
    DIVERGES[`${k}:${view.q(k)?.answer}`] ?? golden.churches[id].cells[k];

  function checkProjection(label: string, viewFor: (id: string) => ChurchView) {
    describe(label, () => {
      test("every one of the 1,340 cells matches", () => {
        const bad: string[] = [];
        for (const id of ids) {
          const view = viewFor(id);
          for (const k of QUESTION_KEYS) {
            const got = colorState(k, view.q(k), ctx);
            const want = expected(id, k, view);
            if (got !== want) bad.push(`${id} ${k}: got ${got}, want ${want}`);
          }
        }
        assert.deepEqual(
          bad.slice(0, 25),
          [],
          `${bad.length} of ${ids.length * QUESTION_KEYS.length} cells wrong` +
            (bad.length > 25 ? " (first 25 shown)" : ""),
        );
      });

      test("every favorScore matches", () => {
        const bad: string[] = [];
        for (const id of ids) {
          const got = favorScore(viewFor(id), ctx);
          const want = golden.churches[id].favorScore;
          // Float sum of 0.3125-style weights: compare at the 2dp the UI shows.
          if (Math.abs(got - want) > 1e-9) bad.push(`${id}: got ${got}, want ${want}`);
        }
        assert.deepEqual(bad.slice(0, 25), [], `${bad.length} favorScore values wrong`);
      });

      test("every favorCount matches", () => {
        const bad: string[] = [];
        for (const id of ids) {
          const got = favorCount(viewFor(id), ctx);
          const want = golden.churches[id].favorCount;
          if (got !== want) bad.push(`${id}: got ${got}, want ${want}`);
        }
        assert.deepEqual(bad.slice(0, 25), [], `${bad.length} favorCount values wrong`);
      });

      /**
       * The golden table stores `steps: null` — not 0 — for the two churches
       * whose next-step pages were never read. That IS the "not checked, never
       * 0 of 8" rule, expressed in the data. Comparing raw `nPresent` here would
       * pass a build that renders a zero where it must render "not checked".
       */
      test("every displayed next-step count matches, and unlooked stays null", () => {
        const bad: string[] = [];
        for (const id of ids) {
          const got = stepsDisplayCount(viewFor(id).steps);
          const want = golden.churches[id].steps ?? null;
          if (got !== want) bad.push(`${id}: got ${got}, want ${want}`);
        }
        assert.deepEqual(bad.slice(0, 25), [], `${bad.length} step counts wrong`);
      });

      test("every platform line matches", () => {
        const bad: string[] = [];
        for (const id of ids) {
          const got = viewFor(id).platformLine;
          const want = golden.churches[id].platformLine;
          if (got !== want) bad.push(`${id}: got ${JSON.stringify(got)}, want ${JSON.stringify(want)}`);
        }
        assert.deepEqual(bad.slice(0, 25), [], `${bad.length} platform lines wrong`);
      });
    });
  }

  const byId = new Map(index.map((r) => [r.id, r]));

  checkProjection("from the full record", (id) => churchFromRecord(loadRecord(id)));
  checkProjection("from the slim index", (id) => churchFromIndex(byId.get(id)!));

  /**
   * Every sanctioned divergence must actually bite.
   *
   * Without this the list is write-only: an entry whose answer value no longer
   * exists, or which someone quietly reverted in `color.ts`, would sit here
   * looking like a deliberate decision while changing nothing — and the next
   * person would read it as documentation of behaviour that is not happening.
   */
  test("each declared divergence applies to real churches, and only where declared", () => {
    for (const [pair, want] of Object.entries(DIVERGES)) {
      const [k, answer] = pair.split(":") as [QuestionKey, string];
      const hit = ids.filter((id) => churchFromRecord(loadRecord(id)).q(k)?.answer === answer);
      assert.ok(hit.length > 0, `${pair} matches no church — the divergence is dead`);
      for (const id of hit) {
        const view = churchFromRecord(loadRecord(id));
        assert.equal(colorState(k, view.q(k), ctx), want, `${id} ${pair}`);
        assert.notEqual(
          golden.churches[id].cells[k],
          want,
          `${pair} is not a divergence — the reference already says ${want}`,
        );
      }
    }
  });

  /**
   * THE REASON THE RECOLOUR IS SAFE, asserted rather than assumed.
   *
   * `favorScore` awards full points for `good`, half for `good2`, and nothing
   * for anything else — so moving an answer between two zero-scoring states
   * must not move a single church's score. The two favor tests above compare
   * against the untouched reference table; this states out loud what makes that
   * still valid, so a future divergence into `good`/`good2` fails HERE, with an
   * explanation, rather than as 134 mysterious favor mismatches.
   */
  test("no divergence moves a church's favor score", () => {
    const scoring = new Set(["good", "good2"]);
    for (const [pair, want] of Object.entries(DIVERGES)) {
      const from = golden.churches[
        ids.find((id) => {
          const a = churchFromRecord(loadRecord(id)).q(pair.split(":")[0] as QuestionKey)?.answer;
          return a === pair.split(":")[1];
        })!
      ].cells[pair.split(":")[0]];
      assert.equal(
        scoring.has(from) || scoring.has(want),
        false,
        `${pair}: ${from} → ${want} crosses the scoring boundary, so favorScore moves`,
      );
    }
  });

  /**
   * The two projections must agree with EACH OTHER, not merely with the table.
   * A future index field that quietly stops being published would show up here
   * first, and this is the assertion that makes the list and the dossier
   * incapable of disagreeing.
   */
  test("the record and index projections agree on every cell", () => {
    const bad: string[] = [];
    for (const id of ids) {
      const a = churchFromRecord(loadRecord(id));
      const b = churchFromIndex(byId.get(id)!);
      for (const k of QUESTION_KEYS) {
        const ca = colorState(k, a.q(k), ctx);
        const cb = colorState(k, b.q(k), ctx);
        if (ca !== cb) bad.push(`${id} ${k}: record ${ca} vs index ${cb}`);
      }
      if (a.country !== b.country) bad.push(`${id} country: ${a.country} vs ${b.country}`);
      if (stepsDisplayCount(a.steps) !== stepsDisplayCount(b.steps))
        bad.push(`${id} steps: record vs index`);
      if (a.name !== b.name) bad.push(`${id} name: ${a.name} vs ${b.name}`);
    }
    assert.deepEqual(bad.slice(0, 25), [], `${bad.length} disagreements between projections`);
  });

  /**
   * The subdivision is the ONE field where the two sources genuinely disagree,
   * and the disagreement is upstream data loss rather than a projection bug:
   * where the scrape spelled a state out in full, the index builder wrote only
   * the country. The record keeps it, the index cannot recover it.
   *
   * Pinned to the exact set so it cannot grow unnoticed — a filter that silently
   * stops returning churches is precisely the kind of quiet shrinkage this
   * codebase fails toward `unknown` to avoid.
   */
  test("subdivision loss in the index is exactly the two known churches", () => {
    const lost: string[] = [];
    for (const id of ids) {
      const a = churchFromRecord(loadRecord(id)).subdiv;
      const b = churchFromIndex(byId.get(id)!).subdiv;
      if (a !== b) lost.push(`${id}: record ${a || "(none)"} vs index ${b || "(none)"}`);
    }
    assert.deepEqual(lost.sort(), [
      "dioms_org: record MS vs index (none)",
      "northwestbible_org: record TX vs index (none)",
    ]);
  });

  /** A country code must never leak into the subdivision dropdown. */
  test("no subdivision value is a country", () => {
    const countries = new Set(index.map((r) => r.co).filter(Boolean));
    const subdivs = new Set(
      index.map((r) => churchFromIndex(r).subdiv).filter(Boolean),
    );
    for (const c of countries) {
      assert.ok(!subdivs.has(c!), `"${c}" is a country and must not be offered as a subdivision`);
    }
  });

  /**
   * q6 specifically, because it is the one the shipped index could not paint and
   * the one an `adapt.ts` refactor would silently re-break. A regression here
   * turns 101 of 134 churches grey in the list while the dossier still shows
   * them green — which reads as missing data rather than as a bug.
   */
  test("q6 paints from the index, not grey (the documented index gap)", () => {
    const tally: Record<string, number> = {};
    for (const id of ids) {
      const s = colorState("q6", churchFromIndex(byId.get(id)!).q("q6"), ctx);
      tally[s] = (tally[s] ?? 0) + 1;
    }
    assert.equal(tally.good, 94, "94 external_handoff churches must read good");
    assert.equal(tally.bad, 7, "7 convenient churches must read bad");
    assert.equal(tally.unk, 33, "only the 33 genuinely-unknown churches may read grey");
  });
});
