/**
 * THE M0 GATE.
 *
 * `dev/golden-colors.json` was generated by EXECUTING the real `colorState`,
 * `favorScore` and `favorCount` out of `core.js`, with default tuning and no
 * colour overrides. Every church x 10 questions, plus a favorScore and a
 * favorCount each — 152,740 cells against the current corpus of 15,274, and it
 * was 1,340 against the 134-church sample this was written for.
 *
 * ONE QUESTION IS CURRENTLY QUARANTINED — see `GOLDEN_STALE` below. The package
 * reworked q8 without regenerating the table, so its q8 column describes the
 * previous corpus. Nine questions and both favor values are still asserted in
 * full.
 *
 * The counts are stated as an ORDER OF MAGNITUDE, not as an assertion: the
 * corpus is republished and the sizes move, so the test below asserts that the
 * golden table and the index cover the same churches rather than that there is
 * some particular number of them.
 *
 * Zero mismatches, or the port is wrong. This is the cheapest possible proof
 * that the most load-bearing logic in the product survived the rewrite, and it
 * catches a precedence bug in `colorState` that no amount of clicking would.
 *
 * IT RUNS TWICE — once from the full records, once from the slim index.
 *
 * That second pass is not redundant. The list, the facet swatches and the
 * histogram are drawn from the index while the dossier is drawn from the record,
 * so a projection that disagrees paints one colour in the list and another in
 * the dossier for the same church. That is the incident the "one source of truth
 * for (question, answer) -> colour" rule exists for, and it is exactly what the
 * index's missing q6 field would have caused. See `adapt.ts`.
 */

import { test, describe } from "node:test";
import assert from "node:assert/strict";

import {
  churchFromIndex,
  churchFromRecord,
  type ChurchView,
} from "../adapt.ts";
import { colorState } from "../color.ts";
import { facetVal, optionState } from "../filter.ts";
import { PATHWAY_STATE } from "../group-types.ts";
import { favorBase, favorCount, favorMax, favorScore, referenceFavorModel } from "../favor.ts";
import { stepsDisplayCount } from "../steps.ts";
import { QMETA, type EngineCtx, type QuestionKey } from "../types.ts";
import { HAVE_FIXTURE, loadGolden, loadIndex, loadRecord } from "./fixture.mts";

const QUESTION_KEYS = QMETA.map(([k]) => k as QuestionKey);

/**
 * WHERE WE HAVE DELIBERATELY STOPPED MATCHING THE REFERENCE.
 *
 * Written out here as a literal, INDEPENDENTLY of `COLOR_PATCH` in `color.ts`
 * and deliberately not imported from it. Importing would make this test say
 * "the code agrees with itself", which is not a fact about anything. Two
 * separate statements of intent mean an unannounced recolour still turns the
 * gate red, and an announced one has to be written down twice — once as
 * behaviour, once as a decision with a reason.
 *
 * `golden-colors.json` stays untouched. It records what the reference `core.js`
 * does, and it has to keep doing that to be worth running.
 */
/**
 * WHERE THE GOLDEN TABLE IS OLDER THAN THE CORPUS IT SHIPPED WITH.
 *
 * NOT a divergence. `DIVERGES` below records places we chose to stop matching the
 * reference; this records a place the reference table is stale, which is an
 * upstream packaging defect and is reported as one.
 *
 * MEASURED, not inferred. `package-v2-final` reworked q8 — 11,591 of 15,274
 * records changed their q8 answer against the previous build (ambiguous →
 * no_app_found 5,817, ambiguous → likely_yes 2,960, unknown → no_app_found 1,334,
 * and five smaller transitions) — but `dev-only/golden-colors.json` is
 * BYTE-IDENTICAL to the previous build's. So the table describes the corpus that
 * was replaced.
 *
 * The quarantine is as narrow as the evidence allows:
 *
 *   - q8 is the only question exempted; the other nine are still asserted cell
 *     for cell across all 15,274 churches, from both projections.
 *   - 3,683 churches whose q8 did not move are still asserted, so the q8 colour
 *     rule itself is under test rather than waved through.
 *   - every exempted church's golden cell is `warn` or `unk` — the colours of
 *     `ambiguous` and `unknown`, which is all the previous build emitted. A
 *     mismatch against a decisive old cell would mean our port is wrong, not that
 *     the table is old, and still fails.
 *   - favorScore and favorCount are NOT exempted. Their expected values are
 *     COMPUTED from the reference table plus q8's own weight, and they match to
 *     the last digit for all 15,274 — which is the proof that q8 is the only
 *     thing that moved.
 *
 * Delete this block the moment a package ships a regenerated golden table.
 */
const GOLDEN_STALE = {
  key: "q8" as QuestionKey,
  /** Pinned so a NEW drift shows up as a changed number rather than as silence. */
  mismatches: 11591,
  matches: 3683,
  /** The only golden values a stale q8 cell may hold: ambiguous, and unknown. */
  cells: ["unk", "warn"],
  /** q8's reference weight, written out rather than imported — `favorScore`
   *  awards the full weight for `good` and half for `good2`. */
  appPts: 0.5,
};

const DIVERGES: Record<string, string> = {
  // A confirmed custom login is `bad`, so a possible one is the "likely" grade
  // of the same finding rather than an unverified signal. The reference says
  // `unver`, whose wording promises a check that was retired upstream.
  // Owner decision. The test below proves it still bites on real churches, so
  // no count is written here to go stale against the next publish.
  "q5:custom_candidate": "bad2",
};

/**
 * REFERENCE tuning, no overrides — the exact conditions golden-colors.json was
 * built under.
 *
 * Deliberately NOT `defaultFavorModel()`. That is the owner's shipped tuning and
 * it moves whenever the product's mind changes about who buys; this table is a
 * proof that the PORT is faithful, and it must not turn red because someone
 * decided mega-churches are worth two points after all.
 */
function makeCtx(rows: ReturnType<typeof loadIndex>): EngineCtx {
  return { overrides: {}, favor: referenceFavorModel(), rows };
}

describe("golden colour + favor table", { skip: !HAVE_FIXTURE && "fixture not present" }, () => {
  const index = loadIndex();
  const golden = loadGolden();
  const ctx = makeCtx(index);
  const ids = Object.keys(golden.churches);

  /**
   * The index and the golden table must describe THE SAME CORPUS.
   *
   * This used to assert `=== 134`, which stopped being a fact the day the
   * fixture became the real operating list and would have to be re-typed after
   * every publish. The number was never the point: what a hard-coded count
   * actually caught was a truncated fixture, and set equality catches that plus
   * the failure a literal could not — a `golden-colors.json` left behind from a
   * different build, which is a live risk now that both files are regenerated
   * together and land as separate bytes in the same package.
   */
  test("the golden table and the index describe the same churches", () => {
    assert.ok(index.length > 0, "the fixture is empty");
    const inIndex = new Set(index.map((r) => r.id));
    const onlyGolden = ids.filter((id) => !inIndex.has(id));
    const onlyIndex = [...inIndex].filter((id) => !golden.churches[id]);
    assert.deepEqual(onlyGolden.slice(0, 10), [], `${onlyGolden.length} golden ids not in the index`);
    assert.deepEqual(onlyIndex.slice(0, 10), [], `${onlyIndex.length} index ids not in the golden table`);
    assert.equal(QUESTION_KEYS.length, 10);
  });

  test("the two denominators are derived, not hard-coded", () => {
    const favor = referenceFavorModel();
    // A church can legitimately score ABOVE favorBase — it is the most you can
    // reach without the custom-website and app opportunities, not a ceiling.
    assert.equal(favorBase(favor), golden.favorBase, "favorBase");
    assert.equal(favorMax(favor), golden.favorMax, "favorMax");
    assert.ok(favorMax(favor) > favorBase(favor), "favorMax must exceed favorBase");
  });

  /**
   * One projection, checked cell by cell. Failures are collected rather than
   * thrown on the first, so a precedence bug reports its whole blast radius
   * instead of one arbitrary church.
   */
  /** The reference value, unless this pair is a sanctioned divergence. */
  const expected = (id: string, k: QuestionKey, view: ChurchView) =>
    DIVERGES[`${k}:${view.q(k)?.answer}`] ?? golden.churches[id].cells[k];

  /**
   * THE SECOND SANCTIONED DIVERGENCE — backends `core.js` had no name for.
   *
   * `VOCAB.BACKEND_NAME` carries 7 of the 19 values the corpus contains, and
   * `platformLine` pushed nothing when it missed. 1,908 churches had a KNOWN
   * backend that appeared nowhere in the product, which is indistinguishable
   * from having detected none. `backend.ts` patches the 11 missing names in.
   *
   * So the reference line is still exactly right about everything it knew; it
   * simply stops one name short. Rather than exempt those churches, the expected
   * value is COMPUTED from the reference: the line is whatever core.js said,
   * plus the name it could not say. A drift in any other direction still fails.
   *
   * The 11 keys are written out here as a literal and deliberately NOT imported
   * from `BACKEND_NAME_PATCH` — the same reasoning as `DIVERGES` above. Importing
   * would make this test assert that the code agrees with itself.
   */
  const NAMED_SINCE: Record<string, string> = {
    rightnowmedia: "RightNow Media",
    pushpay: "Pushpay",
    givelify: "Givelify",
    churchtrac: "ChurchTrac",
    vanco: "Vanco",
    ministrybrands: "Ministry Brands",
    fellowshipone: "Fellowship One",
    textinchurch: "Text In Church",
    rockrms: "Rock RMS",
    clearstream: "Clearstream",
    faithlife: "Faithlife",
  };

  function expectedPlatformLine(id: string, reference: string): string {
    const name = NAMED_SINCE[(byId.get(id)?.pf ?? "").toLowerCase()];
    if (!name) return reference;
    // `platformLine` dedupes: where the builder already reads "Ministry Brands"
    // the backend is not appended a second time, so the reference is unchanged.
    if (reference.toLowerCase().split(" · ").includes(name.toLowerCase())) return reference;
    return reference === "no platform identified" ? name : `${reference} · ${name}`;
  }

  /**
   * What the stale q8 cell costs the reference favor values.
   *
   * `favorScore` awards a question's full weight for `good` and half for `good2`;
   * `favorCount` counts it once for either. Both rules are restated here as
   * literals rather than imported, for the same reason `DIVERGES` is: a
   * correction derived from the code it is correcting proves nothing. Zero when
   * the golden cell still agrees, which is 3,683 churches.
   */
  const scorePts = (s: string) =>
    s === "good" ? GOLDEN_STALE.appPts : s === "good2" ? GOLDEN_STALE.appPts / 2 : 0;
  const countPts = (s: string) => (s === "good" || s === "good2" ? 1 : 0);

  function staleShift(id: string, view: ChurchView) {
    const got = colorState(GOLDEN_STALE.key, view.q(GOLDEN_STALE.key), ctx);
    const want = golden.churches[id].cells[GOLDEN_STALE.key];
    if (got === want) return { score: 0, count: 0, moved: false, got, want };
    return {
      score: scorePts(got) - scorePts(want),
      count: countPts(got) - countPts(want),
      moved: true,
      got,
      want,
    };
  }

  function checkProjection(label: string, viewFor: (id: string) => ChurchView) {
    describe(label, () => {
      test("every cell matches", () => {
        const bad: string[] = [];
        for (const id of ids) {
          const view = viewFor(id);
          for (const k of QUESTION_KEYS) {
            if (k === GOLDEN_STALE.key) continue;
            const got = colorState(k, view.q(k), ctx);
            const want = expected(id, k, view);
            if (got !== want) bad.push(`${id} ${k}: got ${got}, want ${want}`);
          }
        }
        assert.deepEqual(
          bad.slice(0, 25),
          [],
          `${bad.length} of ${ids.length * (QUESTION_KEYS.length - 1)} cells wrong` +
            (bad.length > 25 ? " (first 25 shown)" : ""),
        );
      });

      /**
       * The quarantine, asserted rather than assumed.
       *
       * Two things could hide behind "q8 is stale": a genuinely broken q8 port,
       * and a second question drifting under cover of the first. This pins the
       * exact size of the divergence, requires every exempted church's golden
       * cell to be one the previous build could actually have produced, and
       * requires thousands of churches to still agree.
       */
      test("the stale question diverges only where the old build was undecided", () => {
        const decisive: string[] = [];
        const cells = new Set<string>();
        let moved = 0;
        let held = 0;
        for (const id of ids) {
          const shift = staleShift(id, viewFor(id));
          if (!shift.moved) {
            held++;
            continue;
          }
          moved++;
          cells.add(shift.want);
          if (!GOLDEN_STALE.cells.includes(shift.want)) {
            decisive.push(`${id}: golden ${shift.want} -> ${shift.got}`);
          }
        }
        assert.deepEqual(
          decisive.slice(0, 15),
          [],
          `${decisive.length} churches disagree with a DECISIVE golden ${GOLDEN_STALE.key} cell — ` +
            `that is a port bug, not a stale table`,
        );
        assert.deepEqual([...cells].sort(), [...GOLDEN_STALE.cells].sort());
        assert.equal(moved, GOLDEN_STALE.mismatches, `${GOLDEN_STALE.key} divergence changed size`);
        assert.equal(held, GOLDEN_STALE.matches, `${GOLDEN_STALE.key} agreement changed size`);
      });

      /**
       * NOT exempted. The expected value is the reference value plus q8's own
       * weight — so if anything other than q8 moved, this fails, and it is the
       * assertion that makes the quarantine above safe to grant.
       */
      test("every favorScore matches, once the stale question is paid for", () => {
        const bad: string[] = [];
        for (const id of ids) {
          const view = viewFor(id);
          const got = favorScore(view, ctx);
          const want = golden.churches[id].favorScore + staleShift(id, view).score;
          // Float sum of 0.3125-style weights: compare at the 2dp the UI shows.
          if (Math.abs(got - want) > 1e-9) bad.push(`${id}: got ${got}, want ${want}`);
        }
        assert.deepEqual(bad.slice(0, 25), [], `${bad.length} favorScore values wrong`);
      });

      test("every favorCount matches, once the stale question is paid for", () => {
        const bad: string[] = [];
        for (const id of ids) {
          const view = viewFor(id);
          const got = favorCount(view, ctx);
          const want = golden.churches[id].favorCount + staleShift(id, view).count;
          if (got !== want) bad.push(`${id}: got ${got}, want ${want}`);
        }
        assert.deepEqual(bad.slice(0, 25), [], `${bad.length} favorCount values wrong`);
      });

      /**
       * The golden table stores `steps: null` — not 0 — for the two churches
       * whose next-step pages were never read. That IS the "not checked, never
       * 0 of 8" rule, expressed in the data. Comparing raw `nPresent` here would
       * pass a build that renders a zero where it must render "not checked".
       */
      test("every displayed next-step count matches, and unlooked stays null", () => {
        const bad: string[] = [];
        for (const id of ids) {
          const got = stepsDisplayCount(viewFor(id).steps);
          const want = golden.churches[id].steps ?? null;
          if (got !== want) bad.push(`${id}: got ${got}, want ${want}`);
        }
        assert.deepEqual(bad.slice(0, 25), [], `${bad.length} step counts wrong`);
      });

      test("every platform line matches, apart from the backends core.js could not name", () => {
        const bad: string[] = [];
        for (const id of ids) {
          const got = viewFor(id).platformLine;
          const want = expectedPlatformLine(id, golden.churches[id].platformLine);
          if (got !== want) bad.push(`${id}: got ${JSON.stringify(got)}, want ${JSON.stringify(want)}`);
        }
        assert.deepEqual(bad.slice(0, 25), [], `${bad.length} platform lines wrong`);
      });
    });
  }

  const byId = new Map(index.map((r) => [r.id, r]));

  checkProjection("from the full record", (id) => churchFromRecord(loadRecord(id)));
  checkProjection("from the slim index", (id) => churchFromIndex(byId.get(id)!));

  /**
   * Every sanctioned divergence must actually bite.
   *
   * Without this the list is write-only: an entry whose answer value no longer
   * exists, or which someone quietly reverted in `color.ts`, would sit here
   * looking like a deliberate decision while changing nothing — and the next
   * person would read it as documentation of behaviour that is not happening.
   */
  test("each declared divergence applies to real churches, and only where declared", () => {
    for (const [pair, want] of Object.entries(DIVERGES)) {
      const [k, answer] = pair.split(":") as [QuestionKey, string];
      const hit = ids.filter((id) => churchFromRecord(loadRecord(id)).q(k)?.answer === answer);
      assert.ok(hit.length > 0, `${pair} matches no church — the divergence is dead`);
      for (const id of hit) {
        const view = churchFromRecord(loadRecord(id));
        assert.equal(colorState(k, view.q(k), ctx), want, `${id} ${pair}`);
        assert.notEqual(
          golden.churches[id].cells[k],
          want,
          `${pair} is not a divergence — the reference already says ${want}`,
        );
      }
    }
  });

  /**
   * THE REASON THE RECOLOUR IS SAFE, asserted rather than assumed.
   *
   * `favorScore` awards full points for `good`, half for `good2`, and nothing
   * for anything else — so moving an answer between two zero-scoring states
   * must not move a single church's score. The two favor tests above compare
   * against the untouched reference table; this states out loud what makes that
   * still valid, so a future divergence into `good`/`good2` fails HERE, with an
   * explanation, rather than as 134 mysterious favor mismatches.
   */
  test("no divergence moves a church's favor score", () => {
    const scoring = new Set(["good", "good2"]);
    for (const [pair, want] of Object.entries(DIVERGES)) {
      const from = golden.churches[
        ids.find((id) => {
          const a = churchFromRecord(loadRecord(id)).q(pair.split(":")[0] as QuestionKey)?.answer;
          return a === pair.split(":")[1];
        })!
      ].cells[pair.split(":")[0]];
      assert.equal(
        scoring.has(from) || scoring.has(want),
        false,
        `${pair}: ${from} → ${want} crosses the scoring boundary, so favorScore moves`,
      );
    }
  });

  /**
   * The two projections must agree with EACH OTHER, not merely with the table.
   * A future index field that quietly stops being published would show up here
   * first, and this is the assertion that makes the list and the dossier
   * incapable of disagreeing.
   */
  test("the record and index projections agree on every cell", () => {
    const bad: string[] = [];
    for (const id of ids) {
      const a = churchFromRecord(loadRecord(id));
      const b = churchFromIndex(byId.get(id)!);
      for (const k of QUESTION_KEYS) {
        const ca = colorState(k, a.q(k), ctx);
        const cb = colorState(k, b.q(k), ctx);
        if (ca !== cb) bad.push(`${id} ${k}: record ${ca} vs index ${cb}`);
      }
      if (a.country !== b.country) bad.push(`${id} country: ${a.country} vs ${b.country}`);
      if (stepsDisplayCount(a.steps) !== stepsDisplayCount(b.steps))
        bad.push(`${id} steps: record vs index`);
      if (a.name !== b.name) bad.push(`${id} name: ${a.name} vs ${b.name}`);
    }
    assert.deepEqual(bad.slice(0, 25), [], `${bad.length} disagreements between projections`);
  });

  /**
   * The subdivision is the ONE field where the two sources genuinely disagree,
   * and the disagreement is upstream data loss rather than a projection bug:
   * where the scrape spelled a state out in full, the index builder wrote only
   * the country. The record keeps it, the index cannot recover it.
   *
   * This used to pin the exact two churches, which was a sharp assertion about a
   * 134-church sample and merely a list of names once the corpus became the real
   * one. What it was really protecting is the SHAPE of the disagreement, so that
   * is what is asserted now: the index may be SILENT where the record speaks —
   * that is the known upstream loss — but it may never speak DIFFERENTLY. A
   * record saying TX and an index saying MS is a projection bug and would put a
   * church in the wrong filter; a record saying TX and an index saying nothing
   * only drops it from the dropdown, which is the documented cost.
   */
  test("the index may drop a subdivision but never contradict one", () => {
    const contradictions: string[] = [];
    let upstream = 0;
    let dropped = 0;
    for (const id of ids) {
      const rec = loadRecord(id);
      const row = byId.get(id)!;
      const a = churchFromRecord(rec).subdiv;
      const b = churchFromIndex(row).subdiv;
      if (a === b) continue;
      if (!a || !b) {
        dropped++;
        continue;
      }
      /**
       * THE TWO FIELDS HAVE DIFFERENT FORMATS BY DESIGN, which is why a naive
       * "same input, same output" check gets this backwards.
       *
       *   record  profile.location = "Newton, NC"  -> subdivision is field [1]
       *   index   rg               = "NC, USA"     -> subdivision is field [0]
       *
       * So the readers deliberately take opposite tokens, and identical raw
       * strings are themselves the anomaly: `tokyo_metro_church_jp` carries
       * "国立市, 東京都" in BOTH, and the two faithful readers land on the
       * municipality and the prefecture respectively. That is upstream writing
       * `rg` in the record's format for one church, not a bug in `region.ts`.
       *
       * Counted rather than asserted away, so the day it stops being one church
       * somebody sees it.
       */
      upstream++;
      contradictions.push(`${id}: record ${a} vs index ${b} (raw "${(rec.profile?.location as string) ?? ""}" / "${row.rg ?? ""}")`);
    }
    assert.ok(dropped < ids.length, `every subdivision was dropped (${dropped})`);
    assert.ok(
      upstream < ids.length / 1000,
      `${upstream} churches resolve to two different subdivisions — a data report, ` +
        `not a code fix:\n  ${contradictions.slice(0, 10).join("\n  ")}`,
    );
  });

  /**
   * THE DISCIPLESHIP PROJECTION, BOTH WAYS.
   *
   * The list tile reads `dp`/`dps` off the index; the dossier card reads the
   * pathway out of the full record. Same church, two sources, and if they
   * disagree one surface says "None" while the other says "Not checked" — the
   * precise failure this whole describe block exists to make impossible for
   * colours, applied to the question the tile was just built for.
   *
   * The XOR is asserted rather than trusted. A row carrying neither field falls
   * to "unknown" and under-reports silently; a row carrying both means the
   * projection has two opinions and whichever the code reads first wins.
   */
  test("the index and the record agree about the discipleship pathway", () => {
    const bad: string[] = [];
    const both: string[] = [];
    const neither: string[] = [];
    const tally: Record<string, number> = { has: 0, none: 0, unknown: 0 };

    for (const id of ids) {
      const row = byId.get(id)!;
      if (row.dp != null && row.dps != null) both.push(id);
      if (row.dp == null && row.dps == null) neither.push(id);

      const fromIndex = churchFromIndex(row);
      const fromRecord = churchFromRecord(loadRecord(id));
      tally[fromIndex.pathway]++;

      if (fromIndex.pathway !== fromRecord.pathway) {
        bad.push(`${id}: index ${fromIndex.pathway} vs record ${fromRecord.pathway}`);
      } else if (fromIndex.pathwaySteps !== fromRecord.pathwaySteps) {
        bad.push(`${id}: index ${fromIndex.pathwaySteps} steps vs record ${fromRecord.pathwaySteps}`);
      }
    }

    assert.deepEqual(both.slice(0, 10), [], `${both.length} rows carry BOTH dp and dps`);
    assert.deepEqual(neither.slice(0, 10), [], `${neither.length} rows carry NEITHER dp nor dps`);
    assert.deepEqual(bad.slice(0, 15), [], `${bad.length} churches disagree across the two sources`);

    // All three states must actually occur, or the tile is showing one colour
    // for a reason nobody would notice.
    for (const state of ["has", "none", "unknown"]) {
      assert.ok(tally[state] > 0, `no church reads "${state}" — the three states have collapsed`);
    }
  });

  /**
   * The facet must filter to exactly what the tile shows.
   *
   * A swatch that disagrees with the rows it filters to is the failure this
   * whole block exists to prevent, and a facet is the one place a reader acts on
   * the distinction rather than just reading it: picking "No pathway published"
   * and receiving churches nobody checked is a worked list built on a claim we
   * never made.
   */
  test("the discipleship facet filters to exactly the state it names", () => {
    const bad: string[] = [];
    const seen = new Set<string>();
    for (const id of ids) {
      const view = churchFromIndex(byId.get(id)!);
      const val = facetVal("pathway", view);
      seen.add(val);
      if (val !== view.pathway) bad.push(`${id}: facet ${val} vs tile ${view.pathway}`);
      // The swatch colour is the tile's colour, from one map.
      const { state } = optionState("pathway", val, [view], ctx);
      if (state !== PATHWAY_STATE[view.pathway]) {
        bad.push(`${id}: swatch ${state} vs tile colour ${PATHWAY_STATE[view.pathway]}`);
      }
    }
    assert.deepEqual(bad.slice(0, 10), [], `${bad.length} churches filter to the wrong state`);
    assert.deepEqual([...seen].sort(), ["has", "none", "unknown"], "a facet value went missing");
  });

  /**
   * "None" IS A CLAIM. Only `model_says_no` earns it: we read the site and it
   * publishes no pathway. Every other absence — above all the churches our
   * detector never asked about, which is the largest group in the corpus — must
   * read "not checked", or the console asserts an absence nobody measured.
   */
  test('only a measured negative may read "none"', () => {
    const overclaimed: string[] = [];
    for (const id of ids) {
      const row = byId.get(id)!;
      if (churchFromIndex(row).pathway !== "none") continue;
      if (row.dps !== "model_says_no") overclaimed.push(`${id}: dps=${row.dps}`);
    }
    assert.deepEqual(
      overclaimed.slice(0, 15),
      [],
      `${overclaimed.length} churches would read "None" without a measured negative behind it`,
    );
  });

  /** A country code must never leak into the subdivision dropdown. */
  test("no subdivision value is a country", () => {
    const countries = new Set(index.map((r) => r.co).filter(Boolean));
    const subdivs = new Set(
      index.map((r) => churchFromIndex(r).subdiv).filter(Boolean),
    );
    for (const c of countries) {
      assert.ok(!subdivs.has(c!), `"${c}" is a country and must not be offered as a subdivision`);
    }
  });

  /**
   * q6 specifically, because it is the one the shipped index could not paint and
   * the one an `adapt.ts` refactor would silently re-break. A regression turns
   * churches grey in the list while the dossier still shows them coloured —
   * which reads as missing data rather than as a bug.
   *
   * Asserted as agreement rather than as a tally of three numbers. The tally was
   * a description of one sample; what must hold on any corpus is that the two
   * sources paint the same church the same colour, and that the index has not
   * collapsed the question to grey wholesale.
   */
  test("q6 paints from the index, not grey (the documented index gap)", () => {
    const disagree: string[] = [];
    let good = 0;
    for (const id of ids) {
      const fromIndex = colorState("q6", churchFromIndex(byId.get(id)!).q("q6"), ctx);
      const fromRecord = colorState("q6", churchFromRecord(loadRecord(id)).q("q6"), ctx);
      if (fromIndex !== fromRecord) disagree.push(`${id}: index ${fromIndex} vs record ${fromRecord}`);
      if (fromIndex === "good") good++;
    }
    assert.deepEqual(disagree.slice(0, 10), [], `${disagree.length} churches paint q6 differently`);
    assert.ok(good > 0, "no church reads good from the index — q6 has collapsed to grey again");
  });
});
