/**
 * Entity decoding for scraped display text.
 *
 * The input is church-controlled and the output is rendered next to a real
 * church's name, so the two failure modes are opposite and both matter: leaving
 * `Int&#39;l` on screen reads as corrupted data, and inventing characters that
 * were never on the page is a claim we cannot cite.
 */

import { test, describe } from "node:test";
import assert from "node:assert/strict";

import { decodeEntities } from "../text.ts";
import { answerLabel, evidenceText, recordLabel } from "../labels.ts";
import { rollupWhy, STATE_PHRASE } from "../color.ts";
import { VOCAB } from "../vocab.generated.ts";
import { HAVE_FIXTURE, loadIndex, loadRecord } from "./fixture.mts";

describe("decodeEntities", () => {
  test("decodes what a scraper actually emits", () => {
    assert.equal(decodeEntities("759 W Int&#39;l Ave"), "759 W Int'l Ave");
    assert.equal(decodeEntities("Bright &amp; Early"), "Bright & Early");
    assert.equal(decodeEntities("&quot;Grace&quot;"), '"Grace"');
    assert.equal(decodeEntities("St&#x2019;s"), "St’s");
    assert.equal(decodeEntities("a&nbsp;b"), "a b");
  });

  test("leaves text with no entities completely alone", () => {
    for (const s of ["plain text", "a & b", "100% & rising", ""]) {
      assert.equal(decodeEntities(s), s);
    }
  });

  /**
   * An unknown name is NOT a licence to guess. Printing something the church did
   * not write is worse than printing the entity.
   */
  test("an unrecognised entity is left exactly as found", () => {
    assert.equal(decodeEntities("&hellip;"), "&hellip;");
    assert.equal(decodeEntities("&notarealentity;"), "&notarealentity;");
    assert.equal(decodeEntities("&#xZZZZ;"), "&#xZZZZ;");
    assert.equal(decodeEntities("&#99999999;"), "&#99999999;");
  });

  /** Control characters and lone surrogates would render as nothing at all. */
  test("refuses code points that would vanish on screen", () => {
    assert.equal(decodeEntities("&#0;"), "&#0;");
    assert.equal(decodeEntities("&#7;"), "&#7;", "BEL");
    assert.equal(decodeEntities("&#xD800;"), "&#xD800;", "lone surrogate");
  });

  /**
   * The result is rendered as a TEXT NODE. Decoding `&lt;script&gt;` therefore
   * yields the visible characters `<script>` and nothing executes — but this
   * pins the contract, because the day someone routes this into
   * `dangerouslySetInnerHTML` the decode becomes an injection.
   */
  test("decodes markup to characters, and it must stay a text node", () => {
    assert.equal(
      decodeEntities("&lt;script&gt;alert(1)&lt;/script&gt;"),
      "<script>alert(1)</script>",
    );
  });

  test("never throws, whatever it is handed", () => {
    for (const junk of [null, undefined, 42, {}, [], "&&&;;;", "&#;"]) {
      assert.equal(typeof decodeEntities(junk), "string");
    }
  });
});

describe("recordLabel", () => {
  test("drops the dangling q3 cross-reference and nothing else", () => {
    const real =
      "No explicit discipleship language. However, the church provides multiple clear next steps, " +
      "implying they may have an interest in an organized discipleship process. See Q3 for details.";
    const out = recordLabel(real);
    assert.ok(!/\bQ\d/.test(out), "no literal question number may survive");
    assert.ok(out.endsWith("organized discipleship process."), "the finding itself is untouched");
  });

  test("labels without the cross-reference are returned verbatim", () => {
    for (const s of [
      "Has organized discipleship pathway",
      "Discipleship language present but generic/ambiguous",
      "No login link on the homepage",
    ]) {
      assert.equal(recordLabel(s), s);
    }
  });

  test("it strips the reference, not every mention of a question", () => {
    // Only the trailing boilerplate goes. A label that legitimately discusses
    // something mid-sentence keeps its words.
    assert.equal(recordLabel("Q3 pages were read."), "Q3 pages were read.");
  });

  test("never throws", () => {
    for (const junk of [null, undefined, 42, {}]) {
      assert.equal(typeof recordLabel(junk), "string");
    }
  });
});

/**
 * The evidence paragraph a salesperson may repeat out loud.
 *
 * All 22 `custom_candidate` records carry the same sentence apart from the
 * domain, and it had two problems that only show up when someone says it to a
 * church: it named one competitor for no reason, and it did not mention the one
 * way the finding is commonly wrong.
 *
 * Repaired at render time rather than in the data, for the same reason as the
 * two label repairs — the fixture is regenerated by the pipeline, so an edit
 * there survives exactly until the next drop.
 */
describe("evidenceText", () => {
  const candidate = {
    answer: "custom_candidate",
    evidence:
      "The homepage sign-in link points to the church's own domain (flintbc.net), " +
      "not churchcenter.com — a candidate for a custom login/portal. We have not " +
      "opened the page to confirm it is a bespoke tracked system.",
  };

  test("the competitor aside goes and the church's own domain stays", () => {
    const out = evidenceText("q5", candidate);
    assert.ok(!/churchcenter\.com/i.test(out), "the competitor is still named");
    assert.ok(out.includes("(flintbc.net)"), "the church's own domain IS the finding");
    assert.ok(out.startsWith("The homepage sign-in link points to the church's own domain"));
    assert.ok(!out.includes(" ,"), "the strip left a dangling comma");
  });

  /**
   * The consequential caveat. A staff back-office sign-in on the church's own
   * domain trips the same detector, and a church whose only "custom login" is an
   * admin panel has no member portal — which flips it from a poor lead to a good
   * one. The record never said so.
   */
  test("the admin-login caveat is appended, once", () => {
    const out = evidenceText("q5", candidate);
    assert.match(out, /admin login system/);
    assert.match(out, /manually evaluated as having no custom login system\.$/);
    assert.equal(out.split("admin login system").length - 1, 1);
  });

  test("the caveat is scoped to the answer it is about", () => {
    for (const answer of ["custom_confirmed", "generic_cc", "no_login_link", "unknown"]) {
      const out = evidenceText("q5", { answer, evidence: "Something was found." });
      assert.ok(!/admin login/.test(out), `${answer} should not be hedged`);
    }
    // And to the question. q4 has its own evidence and is not about logins.
    assert.ok(!/admin login/.test(evidenceText("q4", candidate)));
  });

  /**
   * The strip is a CLAUSE, not the string. One `generic_cc` record names its
   * provider as the substance of the finding — removing that would leave a
   * sentence asserting a generic portal without saying which.
   */
  test("a record that names a provider on purpose is left alone", () => {
    const breeze = {
      answer: "generic_cc",
      evidence:
        "The sign-in link points to ccaspen.breezechms.com (Breeze), a rigid generic " +
        "third-party portal rather than the personalized custom login that is a " +
        "big-business specialty.",
    };
    assert.equal(evidenceText("q5", breeze), breeze.evidence);
  });

  test("nothing in, nothing out — and never a crash", () => {
    assert.equal(evidenceText("q5", { answer: "unknown", evidence: "" }), "");
    assert.equal(evidenceText("q5", {}), "");
    assert.equal(evidenceText("q5", null), "");
    assert.equal(evidenceText("q5", undefined), "");
    assert.equal(evidenceText("", { evidence: "kept" }), "kept");
  });

  test("the corpus is clean once repaired", { skip: !HAVE_FIXTURE && "fixture not present" }, () => {
    let candidates = 0;
    for (const row of loadIndex()) {
      const rec = loadRecord(row.id) as { q5?: { answer?: string } };
      const out = evidenceText("q5", rec.q5);
      if (rec.q5?.answer === "custom_candidate") {
        candidates++;
        assert.match(out, /admin login system/, row.id);
      }
      assert.ok(
        !/,\s*not\s+churchcenter\.com/i.test(out),
        `${row.id} still carries the competitor aside`,
      );
    }
    // A floor, not the measured 22. The repair has to keep meeting real
    // `custom_candidate` records for the assertions above to mean anything, but
    // how many there are is a property of the publish and moves with every one.
    assert.ok(candidates > 0, "no custom_candidate records — the repair is unexercised");
  });
});

/**
 * "NOT MEASURED" AND THE COMPETITOR'S NAME.
 *
 * Two wordings a reader was never meant to see, both surviving because the
 * repairs that would have caught them were aimed at the wrong layer.
 *
 * "Not measured" was seven entries in a GENERATED table, so nobody edited it —
 * and it would have been re-generated back anyway.
 *
 * "The Church Center login module is not enabled for this church." is worse: it
 * is not in the code at all. It is a per-church label the pipeline wrote, and a
 * record's own label WINS over the table, so a fix to the table would have
 * silently done nothing. 3,293 churches carry it, most of them not Church Center
 * churches, which makes it a sentence about our detector's configuration
 * printed as a finding about a congregation.
 */
describe("unknown, not unmeasured", () => {
  const ANSWERS = VOCAB.ANSWER_LABEL as Record<string, Record<string, string>>;

  test("no answer label anywhere says 'measured'", () => {
    const bad: string[] = [];
    for (const [k, answers] of Object.entries(ANSWERS)) {
      for (const a of Object.keys(answers)) {
        const label = answerLabel(k, a);
        if (/measured/i.test(label)) bad.push(`${k}:${a} = ${label}`);
      }
    }
    assert.deepEqual(bad, [], "an answer label still uses our word rather than the reader's");
  });

  test("the unmeasured answers all read exactly 'Unknown'", () => {
    for (const [k, a] of [
      ["q1", "unknown"],
      ["q3", "unknown"],
      ["q5", "unknown"],
      ["q6", "unknown"],
      ["q7", "unmeasured"],
      ["q8", "unknown"],
      ["q9", "unknown"],
      ["q10", "unknown"],
    ] as [string, string][]) {
      assert.equal(answerLabel(k, a), "Unknown", `${k}:${a}`);
    }
  });

  /**
   * DROPPED, NOT REWRITTEN. Returning "" is what lets the card fall through to
   * `answerLabel`, so the generic word arrives on its own and no new sentence is
   * invented about a real church. A test that only checked "it no longer says
   * measured" would pass on a label rewritten into a claim nobody made.
   */
  test("a record label that says we did not measure is dropped, not reworded", () => {
    assert.equal(recordLabel("Not measured"), "");
    assert.equal(recordLabel("Service times were not measured."), "");
    assert.equal(recordLabel("Not enough was measured to judge technical capacity."), "");
  });

  test("the detector-configuration sentence is dropped", () => {
    assert.equal(recordLabel("The Church Center login module is not enabled for this church."), "");
  });

  /**
   * The blast radius, checked from the other side. Every one of these names a
   * vendor, and every one of them is a finding about the church rather than
   * about us — `q5.provider` carries the same value. A repair that swept them up
   * would delete the substance of 1,096 cards.
   */
  test("labels that name the vendor a church actually runs are untouched", () => {
    for (const label of [
      "Generic Church Community Builder login — not a custom portal",
      "Generic Church Center login — not a custom portal",
      "Generic Realm login — not a custom portal",
      "Generic Breeze login — not a custom portal",
      "No login link on the homepage",
      "Modern site",
      "No matching app found",
    ]) {
      assert.equal(recordLabel(label), label);
    }
  });

  test("the sub-signal explanation uses the same word as everything else", () => {
    assert.equal(STATE_PHRASE.unk, "unknown");
    const why = rollupWhy([
      { label: "a", state: "good" },
      { label: "b", state: "unk" },
    ] as never);
    assert.ok(!/measured/i.test(why), why);
    assert.match(why, /unknown, not counted/);
    assert.ok(!/measured/i.test(rollupWhy([{ label: "a", state: "unk" }] as never)));
  });

  /**
   * THE WHOLE CORPUS, through the exact expression the dossier renders.
   *
   * The unit tests above pin the rules; this proves no church escapes them. It
   * is the assertion that would have caught the original defect, because it does
   * not care which layer the sentence came from.
   */
  test("no card in the corpus reads either wording", { skip: !HAVE_FIXTURE && "fixture not present" }, () => {
    const CARDS = ["q4", "q5", "q6", "q7", "q8", "q9", "q10"];
    const measured: string[] = [];
    const detector: string[] = [];
    let q5unknown = 0;

    for (const row of loadIndex()) {
      const rec = loadRecord(row.id) as unknown as Record<
        string,
        { label?: unknown; answer?: unknown } | undefined
      >;
      for (const k of CARDS) {
        const shown = recordLabel(rec[k]?.label) || answerLabel(k, String(rec[k]?.answer ?? "unknown"));
        if (/measured/i.test(shown)) measured.push(`${row.id} ${k}: ${shown}`);
        if (/church center login module/i.test(shown)) detector.push(`${row.id} ${k}`);
        if (k === "q5" && rec.q5?.answer === "unknown") {
          q5unknown++;
          assert.equal(shown, "Unknown", `${row.id} q5`);
        }
      }
    }

    assert.deepEqual(measured.slice(0, 10), [], `${measured.length} cards still say "measured"`);
    assert.deepEqual(detector.slice(0, 10), [], `${detector.length} cards still name the detector`);
    // A floor, not the measured 3,293: the repair has to keep meeting real
    // records for the assertion above to mean anything, and the count moves with
    // every publish.
    assert.ok(q5unknown > 0, "no q5 unknown records — the repair is unexercised");
  });
});
