/**
 * Entity decoding for scraped display text.
 *
 * The input is church-controlled and the output is rendered next to a real
 * church's name, so the two failure modes are opposite and both matter: leaving
 * `Int&#39;l` on screen reads as corrupted data, and inventing characters that
 * were never on the page is a claim we cannot cite.
 */

import { test, describe } from "node:test";
import assert from "node:assert/strict";

import { decodeEntities } from "../text.ts";
import { evidenceText, recordLabel } from "../labels.ts";
import { HAVE_FIXTURE, loadIndex, loadRecord } from "./fixture.mts";

describe("decodeEntities", () => {
  test("decodes what a scraper actually emits", () => {
    assert.equal(decodeEntities("759 W Int&#39;l Ave"), "759 W Int'l Ave");
    assert.equal(decodeEntities("Bright &amp; Early"), "Bright & Early");
    assert.equal(decodeEntities("&quot;Grace&quot;"), '"Grace"');
    assert.equal(decodeEntities("St&#x2019;s"), "St’s");
    assert.equal(decodeEntities("a&nbsp;b"), "a b");
  });

  test("leaves text with no entities completely alone", () => {
    for (const s of ["plain text", "a & b", "100% & rising", ""]) {
      assert.equal(decodeEntities(s), s);
    }
  });

  /**
   * An unknown name is NOT a licence to guess. Printing something the church did
   * not write is worse than printing the entity.
   */
  test("an unrecognised entity is left exactly as found", () => {
    assert.equal(decodeEntities("&hellip;"), "&hellip;");
    assert.equal(decodeEntities("&notarealentity;"), "&notarealentity;");
    assert.equal(decodeEntities("&#xZZZZ;"), "&#xZZZZ;");
    assert.equal(decodeEntities("&#99999999;"), "&#99999999;");
  });

  /** Control characters and lone surrogates would render as nothing at all. */
  test("refuses code points that would vanish on screen", () => {
    assert.equal(decodeEntities("&#0;"), "&#0;");
    assert.equal(decodeEntities("&#7;"), "&#7;", "BEL");
    assert.equal(decodeEntities("&#xD800;"), "&#xD800;", "lone surrogate");
  });

  /**
   * The result is rendered as a TEXT NODE. Decoding `&lt;script&gt;` therefore
   * yields the visible characters `<script>` and nothing executes — but this
   * pins the contract, because the day someone routes this into
   * `dangerouslySetInnerHTML` the decode becomes an injection.
   */
  test("decodes markup to characters, and it must stay a text node", () => {
    assert.equal(
      decodeEntities("&lt;script&gt;alert(1)&lt;/script&gt;"),
      "<script>alert(1)</script>",
    );
  });

  test("never throws, whatever it is handed", () => {
    for (const junk of [null, undefined, 42, {}, [], "&&&;;;", "&#;"]) {
      assert.equal(typeof decodeEntities(junk), "string");
    }
  });
});

describe("recordLabel", () => {
  test("drops the dangling q3 cross-reference and nothing else", () => {
    const real =
      "No explicit discipleship language. However, the church provides multiple clear next steps, " +
      "implying they may have an interest in an organized discipleship process. See Q3 for details.";
    const out = recordLabel(real);
    assert.ok(!/\bQ\d/.test(out), "no literal question number may survive");
    assert.ok(out.endsWith("organized discipleship process."), "the finding itself is untouched");
  });

  test("labels without the cross-reference are returned verbatim", () => {
    for (const s of [
      "Has organized discipleship pathway",
      "Discipleship language present but generic/ambiguous",
      "No login link on the homepage",
    ]) {
      assert.equal(recordLabel(s), s);
    }
  });

  test("it strips the reference, not every mention of a question", () => {
    // Only the trailing boilerplate goes. A label that legitimately discusses
    // something mid-sentence keeps its words.
    assert.equal(recordLabel("Q3 pages were read."), "Q3 pages were read.");
  });

  test("never throws", () => {
    for (const junk of [null, undefined, 42, {}]) {
      assert.equal(typeof recordLabel(junk), "string");
    }
  });
});

/**
 * The evidence paragraph a salesperson may repeat out loud.
 *
 * All 22 `custom_candidate` records carry the same sentence apart from the
 * domain, and it had two problems that only show up when someone says it to a
 * church: it named one competitor for no reason, and it did not mention the one
 * way the finding is commonly wrong.
 *
 * Repaired at render time rather than in the data, for the same reason as the
 * two label repairs — the fixture is regenerated by the pipeline, so an edit
 * there survives exactly until the next drop.
 */
describe("evidenceText", () => {
  const candidate = {
    answer: "custom_candidate",
    evidence:
      "The homepage sign-in link points to the church's own domain (flintbc.net), " +
      "not churchcenter.com — a candidate for a custom login/portal. We have not " +
      "opened the page to confirm it is a bespoke tracked system.",
  };

  test("the competitor aside goes and the church's own domain stays", () => {
    const out = evidenceText("q5", candidate);
    assert.ok(!/churchcenter\.com/i.test(out), "the competitor is still named");
    assert.ok(out.includes("(flintbc.net)"), "the church's own domain IS the finding");
    assert.ok(out.startsWith("The homepage sign-in link points to the church's own domain"));
    assert.ok(!out.includes(" ,"), "the strip left a dangling comma");
  });

  /**
   * The consequential caveat. A staff back-office sign-in on the church's own
   * domain trips the same detector, and a church whose only "custom login" is an
   * admin panel has no member portal — which flips it from a poor lead to a good
   * one. The record never said so.
   */
  test("the admin-login caveat is appended, once", () => {
    const out = evidenceText("q5", candidate);
    assert.match(out, /admin login system/);
    assert.match(out, /manually evaluated as having no custom login system\.$/);
    assert.equal(out.split("admin login system").length - 1, 1);
  });

  test("the caveat is scoped to the answer it is about", () => {
    for (const answer of ["custom_confirmed", "generic_cc", "no_login_link", "unknown"]) {
      const out = evidenceText("q5", { answer, evidence: "Something was found." });
      assert.ok(!/admin login/.test(out), `${answer} should not be hedged`);
    }
    // And to the question. q4 has its own evidence and is not about logins.
    assert.ok(!/admin login/.test(evidenceText("q4", candidate)));
  });

  /**
   * The strip is a CLAUSE, not the string. One `generic_cc` record names its
   * provider as the substance of the finding — removing that would leave a
   * sentence asserting a generic portal without saying which.
   */
  test("a record that names a provider on purpose is left alone", () => {
    const breeze = {
      answer: "generic_cc",
      evidence:
        "The sign-in link points to ccaspen.breezechms.com (Breeze), a rigid generic " +
        "third-party portal rather than the personalized custom login that is a " +
        "big-business specialty.",
    };
    assert.equal(evidenceText("q5", breeze), breeze.evidence);
  });

  test("nothing in, nothing out — and never a crash", () => {
    assert.equal(evidenceText("q5", { answer: "unknown", evidence: "" }), "");
    assert.equal(evidenceText("q5", {}), "");
    assert.equal(evidenceText("q5", null), "");
    assert.equal(evidenceText("q5", undefined), "");
    assert.equal(evidenceText("", { evidence: "kept" }), "kept");
  });

  test("the corpus is clean once repaired", { skip: !HAVE_FIXTURE && "fixture not present" }, () => {
    let candidates = 0;
    for (const row of loadIndex()) {
      const rec = loadRecord(row.id) as { q5?: { answer?: string } };
      const out = evidenceText("q5", rec.q5);
      if (rec.q5?.answer === "custom_candidate") {
        candidates++;
        assert.match(out, /admin login system/, row.id);
      }
      assert.ok(
        !/,\s*not\s+churchcenter\.com/i.test(out),
        `${row.id} still carries the competitor aside`,
      );
    }
    // A floor, not the measured 22. The repair has to keep meeting real
    // `custom_candidate` records for the assertions above to mean anything, but
    // how many there are is a property of the publish and moves with every one.
    assert.ok(candidates > 0, "no custom_candidate records — the repair is unexercised");
  });
});
